### ISSUE TITLE
If i have the mod installed, by 8bitdo adapter no longer works with my ds4 controller.

### ISSUE THREAD

**Issue by DeadlyKittenz2005** [cathery/sys-con#58]
I was trying to use a multitude of different controllers while my switch was docked, and tried plugging in my 8bitdo adapter so i could use my ds4 controller, and it didn't work.  I cleared the mod files off of my sd card and the adapter started working again. Is this an issue with the fact that there isn't any ds4 support yet? or is it an issue with the different pieces of hardware not being able to work at the same time.

**Comment by cathery** [comment]
I don't see why it shouldn't work. Even if my sysmodule were to interfere, it would only add the adapter as another controller. Are you using the latest version? What is your FW? Can you launch this diagnostics applet and send me a screenshot of the scan? https://files.catbox.moe/re60qo.rar

**Comment by DeadlyKittenz2005** [comment]
I just installed the latest version, and my firmware is 9.0.1.  I tried it again just to be sure and it's still not working. I'll attach the screenshot of the diagnostics.
![75086829_710760839411476_8753555459949985792_o](https://user-images.githubusercontent.com/24306243/68625757-8a033a80-049f-11ea-8196-ecc4d01797f4.jpg)

**Comment by DeadlyKittenz2005** [comment]
I am using firmware 9.0.1, and the latest version.  I will attach the screenshot of the diagnostics for the ds4 controller.
![75567305_710762186078008_2938972809856024576_o](https://user-images.githubusercontent.com/24306243/68625972-f67e3980-049f-11ea-8dcf-0f5780337824.jpg)

**Comment by cathery** [comment]
The first screenshot is identical to the Xbox One controller protocol and will be recognized as one. The second screenshot should not be touched in any way by the sysmodule, but I think it's a Pro Controller? I think you need to enable "Pro Controller Wired Communication" in System Settings in Controllers and Sensors.

**Comment by DeadlyKittenz2005** [comment]
That's all already enabled. I'm gonna try and manually update the firmware of the adapter itself and then get back to you.

**Comment by Sumpftier** [comment]
I have the exact same Issue

**Comment by DeadlyKittenz2005** [comment]
@Sumpftier ok so i just fixed it, update your adapters firmware to 1.28 the newest on the website.  This seemed to work for me. thanks for the quick responses though @cathery, i'm excited for the roadmap to be completed as much as it can.

**Comment by cathery** [comment]
I'm so glad this issue is resolved, I would've gone insane trying to fix it

**Comment by Sumpftier** [comment]
It still doesnt work for me but ill try to get my hands on another ds4 in a couple of days

**Comment by Sumpftier** [comment]
Btw I have a  Xbox One S controller, a ps3 controller, a wiimote+nunchuck, 2 ps2 controller ( I could buy the usb adapter),a ds4, 3 Xbox360 Controller (with wirelles dongle) and a gamestop wired Xbox one controller. If you need them for testign im ready to help
