### ISSUE TITLE
Xenoblade 2 crash when use DS4 controller

### ISSUE THREAD

**Issue by Yuji6297** [cathery/sys-con#91]
i tried many times with ds4 controller
i enter game -> use the left analog to controll character ( the character run a bit )->  got crash ( error corrupt) 
i got the same issue with usb8bitdo too

Others game work fine, i just test a few game, only xenoblade 2 got crash

Thanks for reading

FW 9.0.1, Atmos 0.9.4
i run sysclock, mod graphic
disable sysclock, mod graphic still got the same issue

**Comment by cathery** [comment]
What is the error code?

**Comment by Yuji6297** [comment]
> What is the error code?

there is no code, just got error and close the game

**Comment by Dantenerosas** [comment]
The same as issue #76 btw

**Comment by Dantenerosas** [comment]
Seems like pretty much the same happens with DS4, sys-con 0.5.1, Atmos 0.9.4, FW 9.0.1 when playing AC3 Remastered. Everything is fine until you are using left analog to move then it crashes

**Comment by AndMeda** [comment]
Xbox 360 controller also crash when I play Xenoblade 2

**Comment by cathery** [comment]
Can anyone install [Atmosphere 0.10.1](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.10.1) and check if it still crashes?

**Comment by cathery** [comment]
I've also released a [new version of sys-con](https://github.com/cathery/sys-con/releases/tag/v0.5.2) for Atmosphere 0.10 and higher

**Comment by Dantenerosas** [comment]
I could try installing it either today or tomorrow but I need to check if every sys module and homebrew I have is compatible with 0.10.1 somehow

**Comment by Dantenerosas** [comment]
@cathery, I've just tested sys-con 0.5.2 + Atmos 0.10.1 + FW 9.0.1 and it still crashes after a bit

**Comment by aria0012** [comment]
Dunno if I should make another thread, but Mortal Kombat 11 crashes as well.

**Comment by Live4ever1** [comment]
I can second the issues as @Dantenerosas has stated. I have even used an XBOX One controller and within app. 30 minutes the game will crash so it is not just DS4 related.

Have not experienced in any other game yet using the DS4 controller.

**Comment by NikScepticeye** [comment]
So I tried syscon and it works like a charm on my DS4 but I'm kinda disappointed though because the main reason I want to use this homebrew is to play Xenoblade 2 and Torna The Golden Country without that pesky JoyCon drift and it crashes whenever I play these two even though it works perfectly on Mario Kart 8, Mario Tennis Aces, Odyssey and even on a demanding ttle Astral Chain so yeah I dont get why it crashes on Xenoblade but works perfectly fine on Astral Chain. btw, it also crashes resident evil 4

**Comment by cathery** [comment]
So I have acquired a copy of Xenoblade 2 to identify and fix the problem. I've made a small change that stopped the crashes. Can someone test this (and other games as well)? https://files.catbox.moe/q1q356.zip

**Comment by Ataraxia13** [comment]
> 
> 
> So I have acquired a copy of Xenoblade 2 to identify and fix the problem. I've made a small change that stopped the crashes. Can someone test this (and other games as well)? https://files.catbox.moe/vstjll.zip

I'm trying this, seems to work.
 I'll play a little longer to see if it crash after a while

**Comment by cathery** [comment]
Somebody has reported that the previous build still crashed in Resident Evil 4 so here's another build to fix that: https://files.catbox.moe/jtwhyf.zip

**Comment by NikScepticeye** [comment]
> Somebody has reported that the previous build still crashed in Resident Evil 4 so here's another build to fix that: https://files.catbox.moe/jtwhyf.zip

Im the one who reported it from GBAtemp and now both games are working fine!
Thanks

**Comment by Yuji6297** [comment]
so, this is the new ver release ?

**Comment by cathery** [comment]
It's a test build with some changes to fix your problem. Install it like usual and tell me if that fixes your issue.

**Comment by cathery** [comment]
I'm going to assume this issue has been fixed. I have released a new version. If crashes still occur with other games, please make a new issue instead.
